apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Cellulant Sonar
  description: |
    Backstage working with SoanrQube.
  annotations:
    #sonarqube.org/project-key: absamonyglobvalidator
    sonarqube.org/project-key: default
spec:
  type: library
  owner: cicd
  lifecycle: testing
